services:
  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      container_name: library-frontend
      ports:
        - "5173:80"
      depends_on:
        - libraryapp
      restart: unless-stopped
  libraryapp:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    
    depends_on:
      mysql:
          condition: service_healthy
          
    restart: always

  mysql:
    image: mysql:8.0
    container_name: Library-mysql

    # ports:
    # - "3306:3306"

    env_file:
      - ./backend/.env

   
      

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 30
    restart: always

    

    volumes:
      - mysql_data:/var/lib/mysql
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - libraryapp
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

volumes:
  mysql_data: